spring:
  application:
    name: Elifoot

  datasource:
    url: jdbc:postgresql://localhost:5432/elifoot-db
    username: leozinho
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: elifoot

  flyway:
    enabled: true
    default-schema: elifoot

